services:
  app:
    build: .
    container_name: tokentide_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=tokentide
    networks:
      - tokentide-network

  db:
    image: postgres:13-alpine
    container_name: tokentide_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tokentide
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tokentide-network

networks:
  tokentide-network:
    driver: bridge

volumes:
  db_data:
    driver: local